services:
  backend:
    build:
      context: ./backend
    container_name: anime-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: anime-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
